config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'

  get 'shop' => 'pages#shop'

  get 'about' =>'pages#about'

  resources :carts
  resources :product_items
  resources :orders
  resources :contacts, only: [:new, :create]
   

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :product_items, dependent: :destroy

	def add_product(product_id)
		current_item = product_items.find_by(product_id: product_id)
		if current_item 
			current_item.quantity += 1
		else
			current_item = product_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		product_items.to_a.sum{|item| item.total_price}

	end
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates :name, :email, presence: true
	validates :message, presence: true, length: {maximum: 300}
end

app/models/order.rb
class Order < ActiveRecord::Base

	has_many :product_items, dependent: :destroy

	validates :name, :email, :address, :city, :country, presence: true


	def add_product_items_from_cart(cart)
		cart.product_items.each do |item|
			item.cart_id = nil
			product_items << item
		end
	end

	def total_price
		product_items.map(&:total_price).sum
	end
end

app/models/product.rb
class Product < ActiveRecord::Base

	before_destroy :ensure_not_product_item

	has_many :product_items

	validates :title, :description, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	def ensure_not_product_item
  		if product_items.empty?
  			return true
  		else
  			errors.add(:base, 'You have Product Items')
  			return false
  		end
  	end

end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
	product.price * quantity 		
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController


	before_action :set_cart, only: [:show, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

	def new
		@cart = Cart.new
	end

	def show
	end

	def destroy
		@cart.destroy if @cart.id == session[:cart_id]
		session[:cart_id] = nil
		redirect_to shop_url, notice: 'Your Cart is Empty'
	end

	private

	def set_cart
		@cart = Cart.find(params[:id])
	end

	def cart_params
		params[:cart]
	end

	def invalid_cart
		logger_error = 'You are trying to access invalid cart'
		redirect_to shop_url, notice: 'Invalid Cart'
	end

end

app/controllers/concerns/current_cart.rb
module CurrentCart

	private

	def set_cart
		@cart = Cart.find(session[:cart_id])
		rescue ActiveRecord::RecordNotFound
		@cart = Cart.create
		session[:cart_id] = @cart.id	
	end	

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	include CurrentCart
	before_action :set_cart, only: [:new, :create]


	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)
		if @contact.save
			redirect_to root_url, notice: 'Thank You For Your Message'
		else
			render :new
		end
	end	

	private


	def contact_params
		params.require(:contact).permit(:name, :email, :message)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	include CurrentCart
	before_action :set_cart, only: [:new, :create]
	before_action :set_order, only: [:show, :edit, :destroy]



	def index
		@orders = Order.all
	end

	def new
		if @cart.product_items.empty?
			redirect_to shop_url, notice: 'Your Cart is Empty'
			return
		end
		@order = Order.new	
		@client_token = Braintree::ClientToken.generate
	end

	def create
		@order = Order.new(order_params)
		if @order.save
			charge
			if @result.success?
				@order.add_product_items_from_cart(@cart)
				Cart.destroy(session[:cart_id])
				session[:cart_id] = nil
				OrderNotifier.received(@order).deliver
				redirect_to root_url, notice: 'Thank you for Your Order!'
			else
				flash[:error] = 'Check Your Cart'
				redirect_to  root_url, alert: @result.message
				@order.destroy
			end
		else	
			@client_token = Braintree::ClientToken.generate	
			render :new
		end
	end

	def show
	end

	def destroy
		@order.destroy
		redirect_to root_url, notice: 'Order deleted'
	end

	private

	def set_order
		@order = Order.find(params[:id])
	end

	def order_params
		params.require(:order).permit(:name, :email, :address, :city, :country)
	end

	def charge
		@result = Braintree::Transaction.sale(
 		amount: @cart.total_price,
  		payment_method_nonce: params[:payment_method_nonce] )
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	include CurrentCart
	before_action :set_cart, only: [:index, :shop, :about]

	
  def index
  	@products = Product.all
  end

  def shop
  	@products = Product.all
  end

  def about
  end
end

app/controllers/product_items_controller.rb
class ProductItemsController < ApplicationController

	include CurrentCart
	before_action :set_cart, only: [:create]
	before_action :set_product_item, only: [:show, :destroy]
	

	def create
		product = Product.find(params[:product_id])
		@product_item = @cart.add_product(product.id)
		if @product_item.save
			redirect_to shop_url, notice: 'Product added to Cart'
		else
			render :new
		end
	end
	
	private

	def set_product_item
		@product_item = ProductItem.find(params[:id])	
	end
	

	def product_item_params
		params.require(:product_item).permit(:product_id)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/_cart.html.erb
<% @cart.product_items.each do |item| %>
			<ul>
				<li>
					<%= item.quantity %>&times;<%= item.product.title %>
					<%= number_to_currency item.total_price %>
				</li>
			</ul>
		<% end %>

app/views/carts/show.html.erb
<div class="container">
	<div class="col-md-12">
		<h2>Carts Details</h2>
		<br>
		<%= render 'carts/cart' %>

		<h5>Total: <%= number_to_currency @cart.total_price %></h5>
		<br>
		<%= button_to 'Checkout', new_order_path, method: :get %>

		<%= link_to 'Back to Store', shop_path %>
		<br>
		<%= link_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'You sure?'} %>
	</div>
</div>

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
	<%= render 'shared/contact_errors' %>


	<form class="contact-form">
	<div>
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
	</div>

	<div>
		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
	</div>

	<div>
		<%= f.label :message %>
		<%= f.text_area :message, class: 'form-control', placeholder: 'Please enter Messages' %>
	</div>

	<div>
		<%= f.submit 'Send' %>
		
	</div>
	</form>

<% end %>

app/views/contacts/new.html.erb
<br>
<br>
<div class="container">
	<%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stigahlid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.braintreegateway.com/js/braintree-2.27.0.min.js' %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="collapse navbar-collapse" id="collapse-navigation">
	<ul class="nav navbar-nav">
		<li>
			<%= link_to 'Home', root_path %>
		</li>
		<li>	
			<%= link_to 'About', about_path %>
		</li>
		<li>	
			<%= link_to 'Contact', new_contact_path %>
		</li>
		<li>
			<%= link_to 'Shop', shop_path %>
		</li>	
<li>
<% if @cart.total_price > 0 %>
		<%= link_to @cart, class: 'menu-cart' do %>
			<i class="fa fa-shopping-cart"></i>
				<%= number_to_currency @cart.total_price %>
				<% end %>
				<% else %>
				<a href="#" class="menu-cart"><i class="fa fa-shopping-cart"></i> $0.00</a>

		

    <% end %>
</li>  
</ul>  

<%= render 'shared/message' %>
<%= yield %>

</body>
</html>

app/views/order_notifier/received.html.erb
<h1>Your order recieved</h1>

<h3> Dear <%= @order.name %></h3>


<p>
  Thank you for your order!
</p>


<p> Your order details </p>

<% @order.product_items.each do |item| %>

	<ul>
		<li>
		<%= item.product.title %>&times;<%= item.quantity %>
		</li>

		<li>
		<%= number_to_currency item.total_price %>
		</li>
	</ul>
<% end %>+

<p> Total: <%= number_to_currency @order.total_price %></p>	

app/views/order_notifier/received.text.erb
OrderNotifier#received

<%= @greeting %>, find me in app/views/order_notifier/received.text.erb

app/views/order_notifier/shipped.html.erb
<h1>Your order shipped</h1>

<h3> Dear <%= @order.name %></h3>


<p>
  we have already shipped your order
</p>


<p> Your order details </p>

<% @order.product_items.each do |item| %>

	<ul>
		<li>
		<%= item.product.title %>&times;<%= item.quantity %>
		</li>
	</ul>
<% end %>+

<p> Thank you!></p>	

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
	<%= render 'shared/msg' %>
		<div class="container">
			<div class="col-md-10">
				<h3>Please Enter Your Details</h3>
			</div>
			
			<div class="form-group">
				<div class="col-md-10">
					<%= f.label :name %>
					<%= f.text_field :name, size: 40, class: 'form-control' %>
				</div>
			</div>		

			<div class="form-group">
				<div class="col-md-10">
					<%= f.label :email %>
					<%= f.email_field :email, size: 40, class: 'form-control' %>
				</div>
			</div>		

			<div class="form-group">
				<div class="col-md-10">
					<%= f.label :address %>
					<%= f.text_area :address, cols: 40, class: 'form-control' %>
				</div>
			</div>		

			<div class="form-group">
				<div class="col-md-10">
					<%= f.label :city %>
					<%= f.text_field :city, size: 40, class: 'form-control' %>
				</div>
			</div>		

			<div class="form-group">
				<div class="col-md-10">
					<%= f.label :country%>
					<%= f.text_field :country, size: 40, class: 'form-control' %>
				</div>
			</div>		

			<div class="form-group">
				<div id="payment-form"></div>
				<div class="col-md-10">
					<%= f.submit 'Place Order' %>
				</div>
			</div>		

		</div>		
<% end %>

app/views/orders/new.html.erb
<div class="container align-vertical hero ">
	<div class="row">
		<div class="col-md-5 text-left">
			<h1> Your order </h1>
		</div>
	</div>
</div>


<br>

	<%= render 'form' %>

<br>


<!-- Script for Braintree -->


<script>
braintree.setup('<%= @client_token %>', 'dropin', {
  container: 'payment-form'
});
</script>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<div class="container">
<h2 class="page-title text-center">Featured Products</h2>

	<%= render 'shared/list' %>


</div>

app/views/pages/shop.html.erb
<div class="container">
	<% @products.each do |product| %>
	<div class="row">
		<div class="col-md-12">
			<div class="product">
				<div class="row">
					<div class="col-md-6 col-xs-12">
						<div class="thumbnail">

							<%= image_tag product.image%>

						</div>
					</div>
					<div class="col-md-5 col-md-offset-1">
						<div class="product-details">
							<h2 class="product-title">
								<%= product.title %>
							</h2>
							<p class="product-price">
								<%= number_to_currency product.price %>
							</p>
							<p>
								<%= product.description %>
							</p>
							<%= button_to product_items_path(product_id: product), class: 'btn btn-default' do %>
								<i class="fa fa-shopping-cart"></i> Add to cart	
							<% end %>	
				</div>
			</div>
		</div>
	</div>			
	<% end %>
</div>

app/views/shared/_contact_errors.html.erb
<% unless @contact.errors.empty? %>
	<script type="text/javascript">
	<% @contact.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_list.html.erb
<div class="container">
	<div class="row products-container">

		<% @products.each do |product| %>
			<% if product.id <= 3 %>
				<div class="col-md-4 col-sm-6 col-xs-12 product">
					<div class="thumbnail" style="background-image: url('/assets/products/<%= product.image_file_name %>');">
						<div class="product-details text-center">
							<div class="align-vertical">
								<h3>
									<%= product.title %>
								</h3>
									<%= link_to root_path, class: 'btn btn-primary' do %>
										<i class="fa fa-shopping-cart"></i> Add to cart
									<% end %>
								<p class="product-price">
									<%= number_to_currency product.price %>
								</p>
							</div>
						</div>
					</div>
				</div>
			<% end %>								

		<% end %> 
	</div>	
</div>	

app/views/shared/_message.html.erb
<% unless flash.empty?%>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
			toastr['<%= type %>'] ('<%= f[1] %>')
		<% end %>

	</script>
<% end %>

app/views/shared/_msg.html.erb
<% unless @order.errors.empty? %>
	<script type="text/javascript">
	<% @order.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>